### PR TITLE
Added capitalize_name function & name_lower function for print

### PR DESCRIPTION
**Pull request by Charles-OpsWerks**

### CODE REVIEW

**Review by clariceandrea — APPROVED** [review]
Noted on this change!

**Review by MrAgui — CHANGES_REQUESTED** [review]
Remove Capitalize Function, change the if condition to accept the print word in any format.

**Review by MrAgui — APPROVED** [review]
sorry got late! thank you for the changes

**Comment by Charles-OpsWerks** [comment]
Thanks!

**Pull request merged**
